#ifndef _INC_PRIME_TC_01_H_
#define _INC_PRIME_TC_01_H_
/*******************************************************************************
 * Includes
 ******************************************************************************/
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>
#include <stddef.h>
#include "unity.h"

/*******************************************************************************
 * Defines
 ******************************************************************************/
#define NUMBER_ELEMENT_OF_ARRAY  10

/*******************************************************************************
 * APIs
 ******************************************************************************/

/*
 * @name: Prime_TC_01
 * ----------------------------
 * @brief: Validates that all numbers generated by `generate_random_numbers` are prime.
 * @param: None.
 * @return: None. The results of the tests are asserted using Unity's TEST_ASSERT_TRUE macro.
 * @note:
 *    This test assumes that the `generate_random_numbers` function generates prime
 *    numbers. It iterates through an array of 10 randomly generated numbers,
 *    checking each one with `is_prime`. If any number is not prime, the test
 *    will fail.
 */
void Prime_TC_01 ( void );

#endif /* _INC_PRIME_TC_01_H_ */
/******************************************************************************
 * EOF
 ******************************************************************************/
