/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "prime_TC_01.h"

/*******************************************************************************
 * Prototypes
 ******************************************************************************/

/*
 * @name: generate_random_numbers
 * ----------------------------
 * @brief: Generates an array of 10 random integers between 0 and 100.
 * @param[in]: arr - Array of size 10 to store the generated random numbers (int32_t[10]).
 * @return: None.
 * @note: None.
 */
static void generate_random_numbers ( int32_t *const arr )
{
    int32_t index = 0; /* Loop counter to iterate through array indices */

    /* Seed the random number generator with the current time */
    srand( (unsigned int) time(NULL) );

    /* Loop to generate 10 random numbers */
    for ( index = 0; index < NUMBER_ELEMENT_OF_ARRAY; ++index )
    {
        /* Generate a random number between 0 and 100 and store it in the array */
        arr[index] = rand() % 101;
    }
}

/*
 * @name: is_prime
 * ----------------------------
 * @brief: Function to check if a number is prime
 * @param[in]: num - The number to be checked for primality (int32_t).
 * @return: A boolean value indicating whether the number is prime (true) or not (false).
 * @note: None
 */
static bool is_prime ( const int32_t num )
{
    bool result = true; /* Assume num is prime unless proven otherwise */

    /* Check if the number is less than or equal to 1, which are not prime numbers */
    if ( num <= 1 )
	{
        result = false;
    }
    /* Check if the number is 2 or 3, both of which are prime */
	else if ( ( num == 2 ) || ( num == 3 ) )
	{
        result = true;
    }
     /* Check if the number is divisible by 2 or 3, in which case it is not prime */
	else if ( ( num % 2 == 0 ) || ( num % 3 == 0 ) )
	{
        result = false;
    }
	else
	{
         /* Loop through numbers starting from 5, incrementing by 6 (Checking 6k ± 1) */
        for (int index = 5; index * index <= num; index += 6)
		{
            /* For each increment, it checks divisibility by index (6k - 1) and index + 2 (6k + 1)
               because all prime numbers greater than 3 are of the form 6k ± 1 */
            if ( ( num % index == 0 ) || ( num % ( index + 2 ) == 0 ) )
			{
                result = false;
                index  = num; /* Break loop */
            }
            else
            {
                /* Do Nothing */
            }
        }
    }

    return result;
}

/*
 * @name: Prime_TC_01
 * ----------------------------
 * @brief: Validates that all numbers generated by `generate_random_numbers` are prime.
 */
void Prime_TC_01 ( void )
{
    int32_t random_arr[NUMBER_ELEMENT_OF_ARRAY] = {0};
    int32_t index          = 0; /* Initialize index variable for loop iteration */

    /* Generate an array of random numbers using the `generate_random_numbers` function */
    generate_random_numbers ( random_arr );

    /* Assert that each element in the random array is a prime number.
       If any element is not prime, the test will fail */
    for ( index = 0; index < NUMBER_ELEMENT_OF_ARRAY; ++index )
    {
        TEST_ASSERT_TRUE( is_prime(random_arr[index]) );
    }
}

/******************************************************************************
 * EOF
 ******************************************************************************/
